# Generated by Django 5.1.6 on 2025-02-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_uploadedimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='category',
            field=models.CharField(choices=[('gallery', 'Gallery'), ('clients', 'Clients'), ('photos', 'Photos'), ('images', 'Images'), ('station', 'Station')], max_length=20),
        ),
    ]
