# Generated by Django 5.1.6 on 2025-02-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_focuscard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='stations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
