# Generated by Django 5.1.6 on 2025-02-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='category',
            field=models.CharField(choices=[('gallery', 'Gallery'), ('clients', 'Clients')], max_length=20),
        ),
    ]
