# Generated by Django 5.1.6 on 2025-02-21 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_galleryandclientimage_services_delete_focuscard'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
