# Generated by Django 5.1.6 on 2025-03-11 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_delete_uploadedimage_alter_contactmessage_last_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
